"""empty message

Revision ID: 4590c5c6480e
Revises: b86eea29be23
Create Date: 2022-02-18 11:36:33.925027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4590c5c6480e'
down_revision = 'b86eea29be23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_created_on'), 'item', ['created_on'], unique=False)
    op.add_column('cart', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('cart', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('cart_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'item', ['item_id'], ['id'])
    op.create_foreign_key(None, 'cart', 'user', ['user_id'], ['id'])
    op.drop_column('cart', 'cart_id')
    op.drop_column('category', 'products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('products', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('cart_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_id_fkey', 'cart', 'user', ['id'], ['id'])
    op.alter_column('cart', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('cart', 'user_id')
    op.drop_index(op.f('ix_item_created_on'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
