"""empty message

Revision ID: a81a73250ff7
Revises: cc97d6ac57ea
Create Date: 2022-02-18 13:48:23.792570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81a73250ff7'
down_revision = 'cc97d6ac57ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('cart', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('cart', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
