"""empty message

Revision ID: b86eea29be23
Revises: 61b6ff4d57b1
Create Date: 2022-02-16 23:25:53.995580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86eea29be23'
down_revision = '61b6ff4d57b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=200), nullable=True))
    op.drop_column('user', 'pasword')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pasword', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
