"""empty message

Revision ID: cc97d6ac57ea
Revises: 4590c5c6480e
Create Date: 2022-02-18 13:39:46.518416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc97d6ac57ea'
down_revision = '4590c5c6480e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'quantity')
    op.drop_column('cart', 'total_cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('total_cost', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
